### PR TITLE
Trying to solve #58 (again)

### PR DESCRIPTION
**Pull request by iblancasa**

### CODE REVIEW

**Comment by iblancasa** [comment]
I am working in it...

**Comment by jsdario** [comment]
Despite travis-ci warning, it does pass the tests. Merging :+1:

**Comment by iblancasa** [comment]
Ok but I want to improve it.
Now, in your travis file you have:
```
 - "./index.js & sleep 3;"
```
It will be ideal to do it in gulp. Why? Because if you are running test in local (or in another CI platform, you will not have to change anything).
I have solved "sleep". Now, I am trying to stop node process

**Comment by jsdario** [comment]
Yeah that is smart. Previous thing was a super patchy workaround.

**Pull request merged**
