### PR TITLE
scanner subscribed to network device request

### PR DESCRIPTION
**Pull request by ankitkhedekar**
Scanner subscribed to a `network/device/request` to which it responds with the cached list of devices in network.

The devices component publishes to it on `componentWillMount`

### CODE REVIEW

**Comment by ankitkhedekar** [comment]
this fixes #91

**Comment by jsdario** [comment]
Code is sharp and precise, works locally. I will test on other devices before publishing to `npm`. Thanks a lot for your contribution 🎆 .

**Comment by ankitkhedekar** [comment]
Thank you for the opportunity. That was my 1st PR

**Comment by jsdario** [comment]
It has been a pleasure – we welcome all contributors to the project and hopefully we have many more like you, @ankitkhedekar.

**Pull request merged**
